### ISSUE TITLE
Broken Filename Column

### ISSUE THREAD

**Issue by littlesunsh9** [hydro-lab/satellite-gage#13]
For some reason attempting to add an additional column for filename (using the "root" name from Part A "Data.R," did not work and halted code in Part B "Discharge.R". please help

**Comment by dmkahler** [comment]
Discharge.R line 6, can't find buffalocali.txt.

**Comment by dmkahler** [comment]
I'm having trouble reproducing Discharge.R without the calibration or transect file.  I don't see any significant issues; so it is likely just a minor issue.

**Comment by dmkahler** [comment]
We found the culprit.  Closing.
